networks:
  pv260.staging:
    driver: bridge

services:
  pv260.api.db.staging:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pv260.api.db.staging
    restart: on-failure
    networks:
      - pv260.staging
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - mssql_data:/var/opt/mssql

  pv260.api.app.staging:
    image: ${IMAGE_NAME}
    container_name: pv260.api.app.staging
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=Staging
      - ConnectionStrings__DefaultConnection=Server=pv260.api.db.staging;Database=PV260;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - pv260.api.db.staging
    networks:
      - pv260.staging
    ports:
      - "${API_PORT}:8080"

volumes:
  mssql_data:
    