name: Run Unit and Inegration Tests

on:
  pull_request:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOTNET_INSTALL_DIR: "~/dotnet"
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install slngen and generate solution file
        run: |
          cd src
          dotnet tool install --global Microsoft.VisualStudio.SlnGen.Tool
          export PATH="$PATH:$HOME/.dotnet/tools"
          slngen dirs.proj -o PV260.sln

      - name: Restore Dependencies
        run: |
          cd src
          dotnet restore PV260.sln

      - name: Build Solution
        run: |
          cd src
          dotnet build PV260.sln --no-restore --configuration Release
        
      - name: Run Tests in Solution
        run: |
          cd src
          dotnet test PV260.sln --no-build --configuration Release
